trigger: none

pr: none

variables:
- name: devEnvironment
  value: dev

resources:
  pipelines:
  - pipeline: LogicAppsHack-CD
    # TODO: Update with the name of your CI pipeline
    source: 'LogicAppsHack CI'
    trigger:
      branches:
      - master

stages:
- stage: DEV
  displayName: 'DEV Deployment'
  variables:
  - template: variables/pipeline-vars.yml
  - group: WhatTheHackVariableGroup

  jobs:
  - deployment: deploy_logicapp_resources
    displayName: Deploy Logic App
    pool:
      vmImage: ubuntu-latest
    environment: $(devEnvironment)
    variables:
      deploymentMode: 'Incremental'
      rg: 'hack-deploy'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            displayName: 'Deploy logic app workflows'
            inputs:
              azureSubscription: 'DavePhelpsConnection'
              appType: 'workflowApp'
              appName: '$(logicAppName)'
              appSettings: '-serviceBus_13_connectionString $(serviceBus) -stockAPIUrl $(stockAPIUrl) -orderAPIUrl $(orderAPIUrl)'
              package: '$(Pipeline.Workspace)/LogicAppsHack-CD/$(logicAppCIArtifactName)/$(resources.pipeline.LogicAppsHack-CD.runID).zip'
              deploymentMethod: 'zipDeploy'
 